version: 2.1

commands:
  redis_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # get redis-cli
            cd /tmp
            wget http://download.redis.io/releases/redis-5.0.8.tar.gz
            tar xvzf redis-5.0.8.tar.gz
            cd redis-5.0.8
            make redis-cli
            sudo cp src/redis-cli /usr/local/bin/
            sudo chmod 755 /usr/local/bin/redis-cli

  common_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Test and install Aibench execs
          command: |
            make test
            make
      - run:
          name: Generate sample data
          command: |
            make data

  redisai_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Load tensors
          command: |
            ./scripts/load_tensors.sh
      - run:
          name: Run inference
          command: |
            ./scripts/run_inference_redisai.sh


jobs:
  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - redis_steps
      - common_steps
      - redisai_steps

  build-multiarch-docker:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_REDISBENCH_PWD" | base64 --decode | docker login --username $DOCKER_REDISBENCH_USER --password-stdin
      - run:
          name: Build
          command: |
            make docker-release
          no_output_timeout: 20m

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge