version: 2.1

commands:
  ci_steps:
    parameters:
      platform:
        type: string
        default: abc
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-redis-cli

      - run:
          name: Install dependencies
          command: |
            # get redis-cli
            cd /tmp
            wget http://download.redis.io/releases/redis-5.0.8.tar.gz
            tar xvzf redis-5.0.8.tar.gz
            cd redis-5.0.8
            make redis-cli
            sudo cp src/redis-cli /usr/local/bin/
            sudo chmod 755 /usr/local/bin/redis-cli

      - save_cache:
          key: v1-{{ arch }}-redis-cli
          paths:
            - /usr/local/bin/redis-cli

      - run:
          name: Install Aibench execs, and load tensors
          command: |
            cd /go/src/github.com/RedisAI/aibench
            go get -t -d ./...
            go test ./...
            ./scripts/build_binaries.sh

      - run:
          name: Generate sample data and load tensors
          command: |
            cd /go/src/github.com/RedisAI/aibench
            ./scripts/generate_data.sh
            ./scripts/load_tensors.sh


jobs:
  build-latest: # test with redisai:latest
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:latest

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - ci_steps:
          platform: debian

  build-v090: # test with redisai:0.9.0
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:0.9.0

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - ci_steps:
        platform: debian

  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - ci_steps:
        platform: debian

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - build-v090
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-latest
      - build-v090