version: 2.1

commands:
  redis_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # get redis-cli
            cd /tmp
            wget http://download.redis.io/releases/redis-5.0.8.tar.gz
            tar xvzf redis-5.0.8.tar.gz
            cd redis-5.0.8
            make redis-cli
            sudo cp src/redis-cli /usr/local/bin/
            sudo chmod 755 /usr/local/bin/redis-cli

  common_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Test and install Aibench execs
          command: |
            make checkfmt
            make get
            make test
            make

  fraud_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Generate sample data for Fraud benchmark (CI)
          command: |
            make data-fraud-ci
      - run:
          name: Load tensors into Redis
          command: |
            ./scripts/load_tensors_redis.sh
      - run:
          name: Run fraud benchmark with TensorFlow Backend (CI) for RedisAI
          command: |
            make bench-fraud-ci

  vision_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install python3 python3-pip
            python3 -m pip install -r ./datasets/vision/coco-2017-val/requirements.txt
      - run:
          name: Generate sample data for Vision benchmark (CI)
          command: |
            make data-vision-ci
      - run:
          name: Run vision benchmark with TensorFlow Backend (CI) for RedisAI
          command: |
            make bench-vision-ci

  vision_steps_tflite:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install --fix-missing python3 python3-pip
            python3 -m pip install -r ./datasets/vision/coco-2017-val/requirements.txt
      - run:
          name: Generate sample data for Vision benchmark (CI)
          command: |
            make data-vision-ci
      - run:
          name: Run vision benchmark with TensorFlow Lite Backend (CI) for RedisAI
          command: |
            make bench-vision-ci-tflite

jobs:
  datasets-ci-fraud: # test with redisai:edge
    docker:
      - image: circleci/golang:1.16
      - image: redislabs/redisai:edge-cpu-bionic

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps
      - redis_steps
      - fraud_steps

  datasets-ci-vision: # test with redisai:edge
    docker:
      - image: circleci/golang:1.16
      - image: redislabs/redisai:edge-cpu-bionic

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps
      - redis_steps
      - vision_steps

  datasets-ci-vision-tflite: # test with redisai:edge
    docker:
      - image: circleci/golang:1.16
      - image: redislabs/redisai:edge-cpu-bionic

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps
      - redis_steps
      - vision_steps_tflite

  build:
    docker:
      - image: circleci/golang:1.16

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps

workflows:
  version: 2
  commit:
    jobs:
      - build
      - datasets-ci-fraud
      - datasets-ci-vision
      - datasets-ci-vision-tflite
  weekly:
    triggers:
      - schedule:
          cron: "00 07 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - datasets-ci-fraud
      - datasets-ci-vision
      - datasets-ci-vision-tflite
