# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-latest: # test with redisai:latest
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:latest

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - run: go get -t -d ./...
      - run: go test ./...

  build-v090: # test with redisai:0.9.0
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:0.9.0

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - run: go get -t -d ./...
      - run: go test ./...

  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - run: go get -t -d ./...
      - run: go test ./...

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - build-v090
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-latest
      - build-v090