version: 2.1

commands:
  redis_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # get redis-cli
            cd /tmp
            wget http://download.redis.io/releases/redis-5.0.8.tar.gz
            tar xvzf redis-5.0.8.tar.gz
            cd redis-5.0.8
            make redis-cli
            sudo cp src/redis-cli /usr/local/bin/
            sudo chmod 755 /usr/local/bin/redis-cli

  redisai_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Test and install Aibench execs
          command: |
            make
            make test

      - run:
          name: Generate sample data and load tensors
          command: |
            make data
            ./scripts/load_tensors.sh


jobs:
  build-latest: # test with redisai:latest
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:latest

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - redis_steps
      - redisai_steps

  build-v090: # test with redisai:0.9.0
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:0.9.0

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - redis_steps
      - redisai_steps

  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - redis_steps
      - redisai_steps

  build-multiarch-docker:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_REDISBENCH_PWD" | base64 --decode | docker login --username $DOCKER_REDISBENCH_USER --password-stdin
      - run:
          name: Build
          command: |
            make docker-release
          no_output_timeout: 20m

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - build-v090
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-latest
      - build-v090