version: 2.1

commands:
  common_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Test and install Aibench execs
          command: |
            make checkfmt
            make get
            make test
            make

jobs:
  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge