version: 2.1

commands:
  ci_steps:
    parameters:
      platform:
        type: string
    steps:
      - run:
          name: Install dependencies
          command: |
            go get -t -d ./...
            go test ./...
            ./scripts/build_binaries.sh

jobs:
  build-latest: # test with redisai:latest
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:latest
    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - ci_steps:
          platform: debian

  build-v090: # test with redisai:0.9.0
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:0.9.0

    working_directory: /go/src/github.com/RedisAI/aibench
      steps:
          - ci_steps:
            platform: debian

  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
      steps:
          - ci_steps:
            platform: debian

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - build-v090
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-latest
      - build-v090