version: 2.1

commands:
  redis_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # get redis-cli
            cd /tmp
            wget http://download.redis.io/releases/redis-6.0.5.tar.gz
            tar xvzf redis-6.0.5.tar.gz
            cd redis-6.0.5
            make redis-cli
            sudo cp src/redis-cli /usr/local/bin/
            sudo chmod 755 /usr/local/bin/redis-cli

  common_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Test and install Aibench execs
          command: |
            make get
            make
      - run:
          name: Generate sample data for Fraud benchmark (CI)
          command: |
            make data-fraud-ci

  redisai_steps:
    parameters:
    steps:
      - checkout
      - run:
          name: Load tensors into Redis
          command: |
            ./scripts/load_tensors_redis.sh
      - run:
          name: Run fraud benchmark (CI) for RedisAI
          command: |
            make bench-fraud-ci

jobs:
  dataset-check-fraud-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/aibench
    steps:
      - checkout
      - common_steps
      - redis_steps
      - redisai_steps

workflows:
  version: 2
  commit:
    jobs:
      - dataset-check-fraud-edge
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - dataset-check-fraud-edge